<?php
//////////////////////////////////
// UserApplePie Version: 1.0.0  //
// http://www.thedavar.com      //
// UserCake Version: 2.0.2      //
// http://usercake.com          //
//////////////////////////////////

echo "<center>";
	echo "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='hr2'>";
    ###Page Title###
	//echo "<title>Car Truck Clubs Disclaimer and Agreement</title>";
		echo "<meta name=\"description\" content=\"Car Truck Clubs Web Site Member Disclimer and Agreement.\">";
	echo "Disclaimer and Agreement"; 

	echo "</td></tr>";
	echo "<tr><td class='content78'>";
?>
<strong>With Agreement of Disclaimer you also agree and have read our 
 <a href='${site_url_link}privacypolicy' title='Privacy Policy' alt='Privacy Policy'>Privacy Policy</a> 
 </strong>
 <br><br>

<strong>CarTruckClubs.com Content </strong> 
<p>Car Truck Clubs Content is provided by its members, and may not be correct or accurate. 
  Please use your best judgement to avoid Scams.  Please Notify CarTruckClubs.com if 
  any content may be misleading or a possible scam. 
  CarTruckClubs.com and Staff does not condone in any illegal activities included within 
  any and all content posted to CarTruckClubs.com. If content within CarTruckClubs.com does not 
  please one, we ask one to no longer visit CarTruckClubs.com. Our content is not here 
  to please everyone, but anyone who enjoys it is welcome. CarTruckClubs.com does not 
  force one to view its content, the choice is yours. All content is reviewed 
  daily, but some unwanted content may not be deleted off CarTruckClubs.com A.S.A.P. With 
  the growing population of CarTruckClubs.com we are unable to make everything perfect. 
</p>
<p><strong>Visitor Age</strong></p>
<p>Visitors to CarTruckClubs.com must be over the age of 18 to view CarTruckClubs.com. If one 
  is under the age of 18 they are required to consult a parent for permission 
  to view CarTruckClubs.com. The reason for CarTruckClubs.com to use this restriction is due to 
  the following:<br>
  -Personal Opinions<br>
  -Possible Graphic Language<br>
  -Possible Graphic Images<br>
  -Anything else that a parent might not want their children to view.<br>
  CarTruckClubs.com and Staff are unable to gain proof of permission for one under 18; 
  therefore, CarTruckClubs.com and Staff are left to assume that one whom is under 18 
  has gained permission from their parent or guardian. If a parent or guardian 
  wishes for their children&#8217;s information to be removed from CarTruckClubs.com please 
  contact CarTruckClubs.com and Staff for more information.</p>
<p><strong>Visitor Personal Information</strong></p>
<p>CarTruckClubs.com will ask for no more than the following information from CarTruckClubs.com 
  visitors when a submission is being created:<br>
  -Name<br>
  -Age<br>
  -E-Mail<br>
  -Location<br>
  This information is stored on a database, and only used for the display of submitted 
  information to CarTruckClubs.com. None of one&#8217;s information will be released from 
  CarTruckClubs.com Staff. If one does not wish to share the above personal information 
  to other visitors then don&#8217;t submit it. </p>
<p>All visitors that visit CarTruckClubs.com are logged every time they visit CarTruckClubs.com. 
  All information collected in this fashion is never to be released. CarTruckClubs.com 
  Logs your computer&#8217;s shared information to enable visitor statistics on 
  CarTruckClubs.com.</p>
<p><strong>E-Mail</strong></p>
<p>CarTruckClubs.com will not send visitors information unrelated to CarTruckClubs.com through e-mail unless otherwise 
  requested. Any and all e-mail addresses submitted to CarTruckClubs.com will not be released 
  or shared. Your e-mail address is important to us at CarTruckClubs.com. We know how 
  it is to receive e-mail spam from other sites sharing e-mail information. So 
  no sharing of e-mail from CarTruckClubs.com</p>
<p><strong>Submissions</strong></p>
<p>In the process of one submitting to CarTruckClubs.com, one agrees not to submit any 
  information that is related to acts of terrorism, vandalism, violence, and unlawful 
  information. If one goes about submitting any of the related information it 
  will be deleted from CarTruckClubs.com. </p>
<p>Please allow time for your submission to be viewable within CarTruckClubs.com. Most 
  submitted content sent to CarTruckClubs.com is directly posted to the site. CarTruckClubs.com 
  and Staff will contact one if information is not complete.</p>
<p>One who is under the age of 18 must have parent permission before submitting 
  information to CarTruckClubs.com. </p>
<p><strong>Image Uploads</strong></p>
<p>CarTruckClubs.com does not allow any explicit or pornographic related images within 
  CarTruckClubs.com. If one is to upload an unwanted image, it will be deleted from CarTruckClubs.com 
  without notice. </p>
<p><strong>Plagiarism</strong></p>
<p>CarTruckClubs.com and Staff believe in original work. If one did not create what one 
  wants to submit to CarTruckClubs.com, then don&#8217;t submit it. CarTruckClubs.com and Staff 
  believe that if one is proud of their work, then the one creator should submit 
  it. If any information submitted to CarTruckClubs.com is plagiarized and proven to be, 
  it will be deleted.</p>
<p><strong>Computer Requirements</strong></p>
<p>CarTruckClubs.com is best viewed with use of the following information:<br>
  -Web Browser: Internet Explorer or Firefox<br>
  -Resolution: 1280x720+<br>
  -Colors: 32 bit+

<bR><br>
</p>
<p><strong>Any and all content within CarTruckClubs.com is subject to change.</strong></p>


<?php

	echo "</td></tr></table>";
	echo "</center>";

?>