<?php
//////////////////////////////////
// UserApplePie Version: 1.1.0  //
// http://www.userapplepie.com  //
// UserCake Version: 2.0.2      //
// http://usercake.com          //
//////////////////////////////////

// Page title
$stc_page_title = "UserApplePie Docs";
// Page Description
$stc_page_description = "UserApplePie Docs.  List of Features in UserApplePie.  Based on UserCake 2.0.2.";
	
// Run Header of page func
style_header_content($stc_page_title, $stc_page_description);
	
	echo "<div align='left'>";
	echo "Welcome to the UserApplePie Docs page.";
	echo "<hr>";
	echo "<h3>UserApplePie Features and Documentation!</h3>";
	echo "<br>
<div class='epboxa'><strong>What is UserApplePie?</strong><br>
  UserApplePie is a FREE open source user management  system.  Its intention is to make  creating your own web site easy and full of features after install.  It can be used as a gaming community website,  employee management website, or a social media website.  <br>
</div><br>
 
<div class='epboxa'><strong>How is UserApplePie beneficial to members?</strong><br>
  UserApplePie is designed to allow members to create a  profile, upload profile photos, post status updates, build a friends list, and  much more.<br>
</div><br>

<div class='epboxa'>
  <strong>What features does UserApplePie offer?</strong><br>
  UserApplePie comes with all features required for a user to  Register, Login, and customize their profile.<br>
  <br>
  <strong>Registration Page</strong><br>
  <em>User Name<br>
  Display Name<br>
  Password<br>
  Confirm Password<br>
  E-Mail Address<br>
  Perform various checks to ensure integrity of user information<br>
  Use of Google&rsquo;s reCAPTCHA<br>
  Add new user to database</em><br>
  <br>
  <strong>Login Page</strong><br>
  <em>Collect username and password OR email and password<br>
  Verify user&rsquo;s login information<br>
  Log user into a secure home page</em><br>
  <br>
  <strong>Edit Profile</strong><br>
  <em>Allow members to update:<br>
  All profile information<br>
  Display name<br>
  Password<br>
  E-Mail setting<br>
  Profile Privacy setting<br>
  Advertisement setting<br>
  Upload Profile photos<br>
  Set Default profile photo<br>
  Add or Delete Friends</em><br>
  <br>
  <strong>View Profile</strong><br>
  <em>Allow users to view a members profile based on the member&rsquo;s  privacy setting<br>
  Allow members to comment on profiles</em><br>
  <br>
  <strong>Home Page</strong><br>
  <em>Display recent friend&rsquo;s activity<br>
  Allow members to post status updates<br>
  Allow members to comment on status updates<br>
  Allow members to sweet(like) posts</em><br>
  <br>
  <strong>Logout Page</strong><br>
  <em>End a member&rsquo;s secure session</em><br>
  <strong><br>
  Forgot Password Page</strong><br>
  <em>Allow user to request a new password via email verification</em><br>
  <br>
  <strong>Resend Activation Page</strong><br>
  <em>Allow user to request the activation email to be resent</em><br>
  <br>
  You can register for this site and try it out before you  install. All freatures included with UserApplePie may not be listed.  </p>
</div>
	";
	echo "<br><br>";
	echo " - More to come.  Please use <a href='".$websiteUrl."Forum/'>Forum</a>.";
	echo "</div>";
	
	
// Run Footer of page func
style_footer_content();

 ?>