<?php
//////////////////////////////////
// UserApplePie Version: 1.0.0  //
// http://www.thedavar.com      //
// UserCake Version: 2.0.2      //
// http://usercake.com          //
//////////////////////////////////

// Page title
$stc_page_title = "UserApplePie Docs";
// Page Description
$stc_page_description = "UserApplePie Docs.  List of Features in UserApplePie.  Based on UserCake 2.0.2.";
	
// Run Header of page func
style_header_content($stc_page_title, $stc_page_description);
	
	echo "<div align='left'>";
	echo "Welcome to the UserApplePie Downloads page.";
	echo "<hr>";
	echo "<h3>Docs Coming Soon!</h3>";
	echo " - Coming Soon.  Please use <a href='".$websiteUrl."Forum/'>Forum</a>.";
	echo "</div>";
	
	
// Run Footer of page func
style_footer_content();

 ?>