<br><br><br><br><br><br>
<hr>

<button href='#Bar' class='btn btn-default visible-xs' data-toggle='collapse'>
	<span class='glyphicon glyphicon-align-left' aria-hidden='true'></span>
</button>


<div id='Bar' class='collapse hidden-sm hidden-md hidden-lg'>
    Show with button and small
</div>

<div class='hidden-xs'>
    Show when not small
</div>


<hr>
<div class='panel panel-default'>
	<div class='panel-body hidden-xs'>
		<div class='row'>
		
			<div class='col-md-6 col-sm-6'>
				<strong>Title</strong>
			</div>

			<div class='col-md-3 col-sm-3'>
				<strong>Statistics</strong>
			</div>

			<div class='col-md-3 col-sm-3' style='text-align: right'>
				<strong>Last Reply</strong>
			</div>
		</div>
	</div>

	<table class='table table-hover'><tr><td>
		<div class='row'>
			<div class='col-md-6 col-sm-6 col-xs-12'>
				<div class='col-xs-10'>
					<h4>
						Title stuff and what not and here we go with all kinds of good info and stuff
					</h4>
				</div>
				<div class='col-xs-2'>
					<button href='#Bar1' class='btn btn-default visible-xs' data-toggle='collapse'>
						<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
					</button>
				</div>
			</div>
			<div id='Bar1' class='collapse hidden-sm hidden-md hidden-lg'>
				<div class='col-md-3 col-sm-3 col-xs-6'>
					12 replies<br>
					22 views<br>
					33 sweets
				</div>

				<div class='col-md-3 col-sm-3 col-xs-6' style='text-align: right'>
					Created by DaVaR<br>
					3 Days ago
				</div>
			</div>
			<div class='hidden-xs'>
				<div class='col-md-3 col-sm-3 col-xs-6'>
					12 replies<br>
					22 views<br>
					33 sweets
				</div>

				<div class='col-md-3 col-sm-3 col-xs-6' style='text-align: right'>
					Created by DaVaR<br>
					3 Days ago
				</div>
			</div>
		</div>
		
	</td></tr><tr><td>

		<div class='row'>
			<div class='col-md-6 col-sm-6 col-xs-12'>
				<div class='col-xs-10'>
					<h4>
						Yest another cool little body panel thingy
					</h4>
				</div>
				<div class='col-xs-2'>
					<button href='#Bar2' class='btn btn-default visible-xs' data-toggle='collapse'>
						<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
					</button>
				</div>
			</div>
			<div id='Bar2' class='collapse hidden-sm hidden-md hidden-lg'>
				<div class='col-md-3 col-sm-3 col-xs-6'>
					3 replies<br>
					12 views<br>
					3 sweets
				</div>

				<div class='col-md-3 col-sm-3 col-xs-6' style='text-align: right'>
					Created by DaVaR<br>
					3 Days ago
				</div>
			</div>
			<div class='hidden-xs'>
				<div class='col-md-3 col-sm-3 col-xs-6'>
					3 replies<br>
					12 views<br>
					3 sweets
				</div>

				<div class='col-md-3 col-sm-3 col-xs-6' style='text-align: right'>
					Created by DaVaR<br>
					3 Days ago
				</div>
			</div>
		</div>
	</td></tr></table>
	
</div>

	
<hr>