<?php
//////////////////////////////////
// UserApplePie Version: 1.0.0  //
// http://www.thedavar.com      //
// UserCake Version: 2.0.2      //
// http://usercake.com          //
//////////////////////////////////

if(!empty($site_adds_bot)){
	echo "<table width='100%' border='0' cellspacing='0' cellpadding='0'><tr><td class='content78' align='center'>";

	echo "$site_adds_bot";
	
	echo "</td></tr></table>";
}
?>